### ISSUE TITLE
maybe something so you cant do something like "const const const const = delete!"

### ISSUE THREAD

**Issue by Jeremy5909** [vivaansinghvi07/dreamberd-interpreter-globals#8]
edited to try to undo

**Comment by Jeremy5909** [comment]
we do a little trolling >:) (sets "const" to "delete")

**Comment by Jeremy5909** [comment]
ok maybe there should be some way to disable public global consts or smtn or idk @vivaansinghvi07

**Comment by vivaansinghvi07** [comment]
maybe i should disable this for keywords 😂

**Comment by Jeremy5909** [comment]
lol it might go against the todepond spirit but this might be necessary.

**Comment by vivaansinghvi07** [comment]
it has been done - i'll consider making it raise an error, but for now, it simply doesn't store it
